In [1]:
grid=[[0,0,0,0,0,0,0,0,0],
      [6,0,0,3,4,0,1,0,0],
      [0,0,1,0,6,0,2,0,0],
      [3,0,4,9,2,0,0,0,0],
      [0,0,0,0,0,0,0,0,9],
      [0,0,0,0,0,0,5,0,6],
      [4,0,0,6,8,0,0,0,0],
      [1,2,0,0,0,4,9,0,0],
      [0,8,0,0,0,0,0,7,0]]

In [2]:
import numpy as np
print(np.matrix(grid))

[[0 0 0 0 0 0 0 0 0]
 [6 0 0 3 4 0 1 0 0]
 [0 0 1 0 6 0 2 0 0]
 [3 0 4 9 2 0 0 0 0]
 [0 0 0 0 0 0 0 0 9]
 [0 0 0 0 0 0 5 0 6]
 [4 0 0 6 8 0 0 0 0]
 [1 2 0 0 0 4 9 0 0]
 [0 8 0 0 0 0 0 7 0]]


In [3]:
def  possible(y,x,n):
    global grid
    for i in range(0,9):
        if grid[y][i] == n:
            return False
    for i in range(0,9):
        if grid[i][x] == n:
            return False
    x0=(x//3)*3
    y0=(y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j]==n:
                return False
    return True

In [4]:
possible(4,4,3)

True

In [6]:
def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x]==0:
                for n in range(1,10):
                    if possible(y,x,n):
                        grid[y][x]=n
                        solve()
                        grid[y][x] = 0
                return
    print(np.matrix(grid))

In [7]:
solve()

[[2 4 5 1 9 7 8 6 3]
 [6 7 8 3 4 2 1 9 5]
 [9 3 1 5 6 8 2 4 7]
 [3 5 4 9 2 6 7 8 1]
 [7 6 2 8 5 1 4 3 9]
 [8 1 9 4 7 3 5 2 6]
 [4 9 7 6 8 5 3 1 2]
 [1 2 6 7 3 4 9 5 8]
 [5 8 3 2 1 9 6 7 4]]


In [1]:

from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

batch_size = 128
num_classes = 10
epochs = 12

# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Using TensorFlow backend.
c:\users\bharg\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\bharg\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\bharg\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16

11493376/11490434 [==============================] - 41s 4us/step


W0328 19:18:21.099018 14204 deprecation_wrapper.py:119] From c:\users\bharg\appdata\local\programs\python\python36\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0328 19:18:21.126948 14204 deprecation_wrapper.py:119] From c:\users\bharg\appdata\local\programs\python\python36\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0328 19:18:21.135921 14204 deprecation_wrapper.py:119] From c:\users\bharg\appdata\local\programs\python\python36\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0328 19:18:21.177808 14204 deprecation_wrapper.py:119] From c:\users\bharg\appdata\local\programs\python\python36\lib\site-packages\keras\backend\tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. P

x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples


W0328 19:18:21.373285 14204 deprecation.py:323] From c:\users\bharg\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 54s 906us/step - loss: 0.2664 - acc: 0.9179 - val_loss: 0.0518 - val_acc: 0.9838
Epoch 2/12
60000/60000 [==============================] - 55s 909us/step - loss: 0.0838 - acc: 0.9751 - val_loss: 0.0427 - val_acc: 0.9856
Epoch 3/12
60000/60000 [==============================] - 54s 900us/step - loss: 0.0657 - acc: 0.9805 - val_loss: 0.0347 - val_acc: 0.9886
Epoch 4/12
60000/60000 [==============================] - 54s 903us/step - loss: 0.0540 - acc: 0.9836 - val_loss: 0.0327 - val_acc: 0.9890
Epoch 5/12
60000/60000 [==============================] - 55s 917us/step - loss: 0.0471 - acc: 0.9859 - val_loss: 0.0333 - val_acc: 0.9891
Epoch 6/12
60000/60000 [==============================] - 55s 918us/step - loss: 0.0411 - acc: 0.9872 - val_loss: 0.0286 - val_acc: 0.9900
Epoch 7/12
60000/60000 [==============================] - 56s 927us/step - loss: 0.0350 - acc: 0.9888 - val_loss: 0.

In [2]:
model.save("digit_rec_model.h5")

In [4]:
from keras.models import load_model

model=load_model("digit_rec_model.h5")

In [6]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 64)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 12, 12, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 9216)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               1179776   
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
__________

In [8]:
print(model.evaluate(x_test, y_test, verbose=0)[1])

0.9916
